// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgxpzuaeorjkcjwwphjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFneHB6dWFlb3Jqa2Nqd3dwaGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzE4MjksImV4cCI6MjA2OTkwNzgyOX0.pCmN3tdq8hlyQ7J4Jd6TF0KDHw7ZNriPMvg8biGPA7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});